<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
    <xsl:template match="/">
        <html xmlns="http://www.w3.org/1999/xhtml">
            <head>
                <title>XML Sitemap</title>
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
                <style type="text/css">
                    body {
                        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
                        color: #334155;
                        background-color: #f8fafc;
                        margin: 0;
                        padding: 3rem 2rem;
                        display: flex;
                        justify-content: center;
                    }
                    .container {
                        max-width: 1000px;
                        width: 100%;
                        background: #ffffff;
                        padding: 3rem;
                        border-radius: 16px;
                        box-shadow: 0 4px 30px rgba(0, 0, 0, 0.03);
                    }
                    h1 {
                        color: #0f172a;
                        font-size: 2.25rem;
                        margin-top: 0;
                        margin-bottom: 0.75rem;
                        font-weight: 800;
                        font-family: Georgia, Cambria, "Times New Roman", Times, serif;
                    }
                    p {
                        font-size: 0.95rem;
                        line-height: 1.6;
                        color: #64748b;
                        margin: 0.5rem 0;
                    }
                    p.info {
                        margin-top: 2rem;
                        font-size: 0.95rem;
                        font-weight: 500;
                        color: #475569;
                    }
                    a {
                        color: #c27a25;
                        text-decoration: none;
                        font-weight: 600;
                    }
                    a:hover {
                        text-decoration: underline;
                    }
                    table {
                        width: 100%;
                        border-collapse: collapse;
                        margin-top: 2rem;
                        text-align: left;
                    }
                    th {
                        background-color: #f8fafc;
                        color: #0f172a;
                        font-size: 0.75rem;
                        font-weight: 800;
                        letter-spacing: 0.05em;
                        text-transform: uppercase;
                        padding: 1rem;
                        border-bottom: 1px solid #e2e8f0;
                    }
                    td {
                        padding: 1.25rem 1rem;
                        border-bottom: 1px solid #f1f5f9;
                        font-size: 0.9rem;
                        word-break: break-all;
                    }
                    tr:nth-child(even) td {
                        background-color: #fcfdfe;
                    }
                    tr:hover td {
                        background-color: #f8fafc;
                    }
                    .count {
                        color: #c27a25;
                        font-weight: bold;
                    }
                    .img-badge {
                        background: #f1f5f9;
                        color: #475569;
                        padding: 2px 8px;
                        border-radius: 9999px;
                        font-size: 0.75rem;
                        font-weight: 600;
                        display: inline-block;
                        margin-top: 0.25rem;
                    }
                </style>
            </head>
            <body>
                <div class="container">
                    <h1>XML Sitemap</h1>
                    
                    <xsl:choose>
                        <!-- Check if it is a Sitemap Index -->
                        <xsl:when test="sitemap:sitemapindex">
                            <p>Generated by Bag Vaults' custom SEO engine. This is an XML Sitemap Index, meant for consumption by search engines.</p>
                            <p>You can find more information about XML sitemaps on <a href="https://sitemaps.org" target="_blank">sitemaps.org</a>.</p>
                            <p class="info">This XML Sitemap Index file contains <span class="count"><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/></span> sitemaps.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <th style="width: 70%">Sitemap URL</th>
                                        <th style="width: 30%">Last Modified</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                                        <tr>
                                            <td>
                                                <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
                                            </td>
                                            <td>
                                                <xsl:value-of select="sitemap:lastmod"/>
                                            </td>
                                        </tr>
                                    </xsl:for-each>
                                </tbody>
                            </table>
                        </xsl:when>
                        
                        <!-- Check if it is a URL Set -->
                        <xsl:otherwise>
                            <p>Generated by Bag Vaults' custom SEO engine. This is an XML Sitemap, meant for consumption by search engines.</p>
                            <p>You can find more information about XML sitemaps on <a href="https://sitemaps.org" target="_blank">sitemaps.org</a>.</p>
                            <p class="info">This XML Sitemap contains <span class="count"><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></span> URLs.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <th style="width: 55%">URL</th>
                                        <th style="width: 12%">Change Freq</th>
                                        <th style="width: 8%">Priority</th>
                                        <th style="width: 25%">Last Modified</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <xsl:for-each select="sitemap:urlset/sitemap:url">
                                        <tr>
                                            <td>
                                                <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
                                                <xsl:if test="image:image">
                                                    <br/>
                                                    <span class="img-badge">
                                                        Images: <xsl:value-of select="count(image:image)"/>
                                                    </span>
                                                </xsl:if>
                                            </td>
                                            <td>
                                                <xsl:value-of select="sitemap:changefreq"/>
                                            </td>
                                            <td>
                                                <xsl:value-of select="sitemap:priority"/>
                                            </td>
                                            <td>
                                                <xsl:value-of select="sitemap:lastmod"/>
                                            </td>
                                        </tr>
                                    </xsl:for-each>
                                </tbody>
                            </table>
                        </xsl:otherwise>
                    </xsl:choose>
                </div>
            </body>
        </html>
    </xsl:template>
</xsl:stylesheet>
